name: 'Obsidian release pipeline'
description: 'Creates releases for obsidian plugins'
author: '4Source'

# Define your inputs here.
inputs:
  
# Define your outputs here.
outputs:

runs:
  using: node20
  main: dist/index.js
